// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf10iIiuvDaq35TBXMRZdgSyyYVyQibz0',
    appId: '1:65361462968:web:91976a706a5dc51dc2564d',
    messagingSenderId: '65361462968',
    projectId: 'little-one-40dc6',
    authDomain: 'little-one-40dc6.firebaseapp.com',
    storageBucket: 'little-one-40dc6.appspot.com',
    measurementId: 'G-B92EQZXK1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMfzRnHSB32HggCgknlh8EJwQwNaLGR-o',
    appId: '1:65361462968:android:f3f5b535c9e6ec48c2564d',
    messagingSenderId: '65361462968',
    projectId: 'little-one-40dc6',
    storageBucket: 'little-one-40dc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLgfAPbHHbgaHxoSJY0pUIMm4gm7luZzU',
    appId: '1:65361462968:ios:24dedbd9511945f0c2564d',
    messagingSenderId: '65361462968',
    projectId: 'little-one-40dc6',
    storageBucket: 'little-one-40dc6.appspot.com',
    iosClientId: '65361462968-9tvr083rd8fc26i8c20jbu4lvc6h7i80.apps.googleusercontent.com',
    iosBundleId: 'com.example.littleOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLgfAPbHHbgaHxoSJY0pUIMm4gm7luZzU',
    appId: '1:65361462968:ios:24dedbd9511945f0c2564d',
    messagingSenderId: '65361462968',
    projectId: 'little-one-40dc6',
    storageBucket: 'little-one-40dc6.appspot.com',
    iosClientId: '65361462968-9tvr083rd8fc26i8c20jbu4lvc6h7i80.apps.googleusercontent.com',
    iosBundleId: 'com.example.littleOne',
  );
}
